#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-brotlicffi
Version  : 1.0.9.2
Release  : 1
URL      : https://files.pythonhosted.org/packages/d3/d8/6acbb65e350213ad6bd96180593fad0a269a3baa845c67fed21adee3959d/brotlicffi-1.0.9.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/d3/d8/6acbb65e350213ad6bd96180593fad0a269a3baa845c67fed21adee3959d/brotlicffi-1.0.9.2.tar.gz
Summary  : Python CFFI bindings to the Brotli library
Group    : Development/Tools
License  : MIT
Requires: pypi-brotlicffi-license = %{version}-%{release}
Requires: pypi-brotlicffi-python = %{version}-%{release}
Requires: pypi-brotlicffi-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(cffi)
BuildRequires : pypi(enum34)

%description
==========

%package license
Summary: license components for the pypi-brotlicffi package.
Group: Default

%description license
license components for the pypi-brotlicffi package.


%package python
Summary: python components for the pypi-brotlicffi package.
Group: Default
Requires: pypi-brotlicffi-python3 = %{version}-%{release}

%description python
python components for the pypi-brotlicffi package.


%package python3
Summary: python3 components for the pypi-brotlicffi package.
Group: Default
Requires: python3-core
Provides: pypi(brotlicffi)
Requires: pypi(cffi)
Requires: pypi(enum34)

%description python3
python3 components for the pypi-brotlicffi package.


%prep
%setup -q -n brotlicffi-1.0.9.2
cd %{_builddir}/brotlicffi-1.0.9.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1638626268
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-brotlicffi
cp %{_builddir}/brotlicffi-1.0.9.2/LICENSE %{buildroot}/usr/share/package-licenses/pypi-brotlicffi/bae61d713726c8dbf4b43a6bf0ddeb04e1f927cd
cp %{_builddir}/brotlicffi-1.0.9.2/libbrotli/LICENSE %{buildroot}/usr/share/package-licenses/pypi-brotlicffi/c045813a6c514f2d30d60a07c6aaf3603850e608
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-brotlicffi/bae61d713726c8dbf4b43a6bf0ddeb04e1f927cd
/usr/share/package-licenses/pypi-brotlicffi/c045813a6c514f2d30d60a07c6aaf3603850e608

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
